### ISSUE TITLE
Future npm package plans

### ISSUE THREAD

**Issue by levithomason** [aldanor/semantic-ui-react#7]
Hey there, glad to find another SUI + React project out in the wild. I'm the author of [Stardust](https://github.com/TechnologyAdvice/stardust), which is now the official SUI React integration.  We've outlined our path to migrating to the official Semantic-Org [on this issue](https://github.com/TechnologyAdvice/stardust/issues/243).  Part of this includes publishing a new NPM package which would ideally have the current name your package, `semantic-ui-react`.  This would allow us to follow the current official package naming scheme:

`semantic-ui-css`
`semantic-ui-less`
`semantic-ui-sass`
`semantic-ui-ember`
...etc

If there are no plans to continue work on `semantic-ui-react`, would you be willing to consider transferring the package for official use?  The package name is not a deal breaker for us, but it would be a big help and super appreciated.

No matter what you decide, I'd love to have your eyes and hands on official integration as well ;)

**Comment by levithomason** [comment]
@aldanor bump

**Comment by aldanor** [comment]
@levithomason Hi, I must have missed the notification. Yes, I think there's no problem in transferring the npm package over if you'll describe how to proceed with it, I'm not planning to continue working on this as of right now since I've got a boatload of other stuff to finish :/

Glad someone's doing the official integration (attempt number 5?), hope this one takes off!

**Comment by levithomason** [comment]
Awesome, thanks.  If you want to add me as a package [owner](https://docs.npmjs.com/cli/owner) that should take care of it for now:

``` shell
npm owner add levithomason semantic-ui-react
```

Once we're ready to publish, I can deprecate the current release and publish the new one.

**Comment by aldanor** [comment]
https://www.npmjs.com/package/semantic-ui-react

@levithomason Done and done 🐼

**Comment by aldanor** [comment]
Hope that solves it!

**Comment by levithomason** [comment]
😄 that was quick!
